FROM apache/airflow:2.10.4-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir dbt-core==1.11.14 dbt-postgres==1.11.0 sqlparse==0.6.0 kafka-python==3.0.10 psycopg[binary]==3.2.3 pandas==2.2.3
