FROM python:3.11-slim

WORKDIR /opt/customer-360-cdc-platform
COPY requirements.txt .
RUN pip install --no-cache-dir fastapi==0.141.1 starlette==1.3.1 uvicorn[standard]==0.32.1
COPY . .
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
